"""Add Task Model

Revision ID: f9b6642c4dc1
Revises: 00896204b438
Create Date: 2025-12-19 12:11:03.791139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b6642c4dc1'
down_revision: Union[str, Sequence[str], None] = '00896204b438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('custom_fields_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_fields_config_entity'), 'custom_fields_config', ['entity'], unique=False)
    op.create_index(op.f('ix_custom_fields_config_id'), 'custom_fields_config', ['id'], unique=False)
    op.create_index(op.f('ix_custom_fields_config_key'), 'custom_fields_config', ['key'], unique=False)
    op.create_table('discount_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rules_id'), 'discount_rules', ['id'], unique=False)
    op.create_table('product_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_families_id'), 'product_families', ['id'], unique=False)
    op.create_index(op.f('ix_product_families_name'), 'product_families', ['name'], unique=False)
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_types_id'), 'product_types', ['id'], unique=False)
    op.create_index(op.f('ix_product_types_name'), 'product_types', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.add_column('clients', sa.Column('custom_attributes', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('discount_value', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('net_unit_price', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('rule_snapshot', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('custom_attributes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('family_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('custom_attributes', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'products', 'product_types', ['type_id'], ['id'])
    op.create_foreign_key(None, 'products', 'product_families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'custom_attributes')
    op.drop_column('products', 'type_id')
    op.drop_column('products', 'family_id')
    op.drop_column('products', 'brand_id')
    op.drop_column('orders', 'custom_attributes')
    op.drop_column('order_items', 'rule_snapshot')
    op.drop_column('order_items', 'net_unit_price')
    op.drop_column('order_items', 'discount_value')
    op.drop_column('clients', 'custom_attributes')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_product_types_name'), table_name='product_types')
    op.drop_index(op.f('ix_product_types_id'), table_name='product_types')
    op.drop_table('product_types')
    op.drop_index(op.f('ix_product_families_name'), table_name='product_families')
    op.drop_index(op.f('ix_product_families_id'), table_name='product_families')
    op.drop_table('product_families')
    op.drop_index(op.f('ix_discount_rules_id'), table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_custom_fields_config_key'), table_name='custom_fields_config')
    op.drop_index(op.f('ix_custom_fields_config_id'), table_name='custom_fields_config')
    op.drop_index(op.f('ix_custom_fields_config_entity'), table_name='custom_fields_config')
    op.drop_table('custom_fields_config')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
