import sys
import os

filepath = "alembic/versions/346ec68a36b2_init.py"

with open(filepath, "r") as f:
    lines = f.readlines()

new_lines = []
mode = "normal" # normal, upgrade, downgrade

for i, line in enumerate(lines):
    # Detect start of upgrade
    if "def upgrade() -> None:" in line:
        new_lines.append(line)
        mode = "upgrade"
        continue

    if "def downgrade() -> None:" in line:
        new_lines.append(line)
        mode = "downgrade"
        continue
        
    if mode == "upgrade":
        if '"""Upgrade schema."""' in line:
            new_lines.append(line)
            # Insert logic
            new_lines.append("    context = op.get_context()\n")
            new_lines.append("    scope = context.get_x_argument(as_dictionary=True).get('scope')\n")
            new_lines.append("    if not scope:\n")
            new_lines.append("        scope = 'system'\n")
            new_lines.append("    # ### commands auto generated by Alembic - please adjust! ###\n")
            new_lines.append("    if scope == 'system':\n")
            continue
        
        if "op.create_table('areas'," in line and "schema='public'" not in "".join(lines[i:i+20]): # Heuristic for tenant areas
             # This heuristic is weak if schema='public' is far down.
             # Better: Split by known line index? 
             # Original file line 150.
             # But line numbers shifted due to insertions.
             # Search for the specific tenant area creation block.
             pass

    # Actually, hardcoding line ranges is safer given I know the file structure from Step 96.
    # But line numbers change.
    
    # Better approach:
    # Just write the whole file content that I verify.
    pass

# Direct write approach
content = r'''"""Init

Revision ID: 346ec68a36b2
Revises: 
Create Date: 2026-01-05 16:54:10.916628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346ec68a36b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    context = op.get_context()
    scope = context.get_x_argument(as_dictionary=True).get('scope')
    if not scope:
        print("WARNING: scope missing, defaulting to system")
        scope = 'system'

    # ### commands auto generated by Alembic - please adjust! ###
    if scope == 'system':
        op.create_table('tenants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('setup_pending', 'active', 'suspended', name='tenantstatus'), nullable=True),
        sa.Column('fiscal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('plan_type', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('commercial_info', sa.Text(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('demo_mode_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_index(op.f('ix_public_tenants_name'), 'tenants', ['name'], unique=False, schema='public')
        op.create_index(op.f('ix_public_tenants_slug'), 'tenants', ['slug'], unique=True, schema='public')
        op.create_table('shadow_backups',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_slug', sa.String(), nullable=True),
        sa.Column('table_name', sa.String(), nullable=True),
        sa.Column('record_id', sa.String(), nullable=True),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_shadow_backups_table_name'), 'shadow_backups', ['table_name'], unique=False)
        op.create_index(op.f('ix_shadow_backups_tenant_slug'), 'shadow_backups', ['tenant_slug'], unique=False)
        op.create_table('api_keys',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('key', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('scopes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_index(op.f('ix_public_api_keys_key'), 'api_keys', ['key'], unique=True, schema='public')
        op.create_table('areas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('icon', sa.String(), nullable=True),
        sa.Column('pages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_table('invites',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_index(op.f('ix_public_invites_code'), 'invites', ['code'], unique=True, schema='public')
        op.create_table('roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('access_level', sa.Enum('GLOBAL', 'TEAM', 'OWN', name='accesslevel'), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_table('global_users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('recovery_email', sa.String(), nullable=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('role_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_index(op.f('ix_public_global_users_username'), 'global_users', ['username'], unique=True, schema='public')
        op.create_table('role_area_association',
        sa.Column('role_id', sa.UUID(), nullable=True),
        sa.Column('area_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['area_id'], ['public.areas.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
        sa.PrimaryKeyConstraint('role_id', 'area_id'),
        schema='public'
        )
        op.create_table('global_tasks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('assignee_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['assignee_id'], ['public.global_users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_index(op.f('ix_public_global_tasks_title'), 'global_tasks', ['title'], unique=False, schema='public')
        op.create_table('memberships',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['public.global_users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_table('user_grid_preferences',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('grid_id', sa.String(), nullable=True),
        sa.Column('columns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['public.global_users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
        )
        op.create_index(op.f('ix_public_user_grid_preferences_grid_id'), 'user_grid_preferences', ['grid_id'], unique=False, schema='public')

    if scope == 'tenant':
        op.create_table('areas',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('icon', sa.String(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('pages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
        op.create_index(op.f('ix_areas_slug'), 'areas', ['slug'], unique=True)
        op.create_table('brands',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('clients',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
        op.create_table('custom_fields_config',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('entity', sa.String(), nullable=True),
        sa.Column('key', sa.String(), nullable=True),
        sa.Column('label', sa.String(), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('required', sa.Boolean(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_custom_fields_config_entity'), 'custom_fields_config', ['entity'], unique=False)
        op.create_index(op.f('ix_custom_fields_config_key'), 'custom_fields_config', ['key'], unique=False)
        op.create_table('discount_rules',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('discount_percent', sa.Float(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('products_categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('suppliers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('table_definitions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('icon', sa.String(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_table_definitions_name'), 'table_definitions', ['name'], unique=False)
        op.create_table('tasks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('webhook_subscriptions',
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('target_url', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('event_type')
        )
        op.create_table('field_definitions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('table_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'CURRENCY', 'DATE', 'DATETIME', 'BOOLEAN', 'SELECT', 'MULTI_SELECT', 'RELATION', 'IMAGE', 'FILE', 'FORMULA', 'LOOKUP', name='fieldtype'), nullable=True),
        sa.Column('is_required', sa.Boolean(), nullable=True),
        sa.Column('is_unique', sa.Boolean(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.Column('default_value', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['table_id'], ['table_definitions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_field_definitions_name'), 'field_definitions', ['name'], unique=False)
        op.create_table('orders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=True),
        sa.Column('representative_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('total_value', sa.Float(), nullable=True),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
        op.create_table('products',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('sku', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('category_id', sa.UUID(), nullable=True),
        sa.Column('brand_id', sa.UUID(), nullable=True),
        sa.Column('supplier_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['products_categories.id'], ),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
        op.create_table('view_definitions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('table_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('view_type', sa.String(), nullable=True),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['table_id'], ['table_definitions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('order_items',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('order_id', sa.UUID(), nullable=True),
        sa.Column('product_id', sa.UUID(), nullable=True),
        sa.Column('quantity', sa.Float(), nullable=True),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('net_unit_price', sa.Float(), nullable=True),
        sa.Column('total', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    context = op.get_context()
    scope = context.get_x_argument(as_dictionary=True).get('scope')

    # ### commands auto generated by Alembic - please adjust! ###
    if scope == 'tenant':
        op.drop_table('order_items')
        op.drop_table('view_definitions')
        op.drop_index(op.f('ix_products_name'), table_name='products')
        op.drop_table('products')
        op.drop_index(op.f('ix_orders_status'), table_name='orders')
        op.drop_table('orders')
        op.drop_index(op.f('ix_field_definitions_name'), table_name='field_definitions')
        op.drop_table('field_definitions')
        op.drop_table('webhook_subscriptions')
        op.drop_table('tasks')
        op.drop_index(op.f('ix_table_definitions_name'), table_name='table_definitions')
        op.drop_table('table_definitions')
        op.drop_table('suppliers')
        op.drop_table('products_categories')
        op.drop_table('discount_rules')
        op.drop_index(op.f('ix_custom_fields_config_key'), table_name='custom_fields_config')
        op.drop_index(op.f('ix_custom_fields_config_entity'), table_name='custom_fields_config')
        op.drop_table('custom_fields_config')
        op.drop_index(op.f('ix_clients_name'), table_name='clients')
        op.drop_table('clients')
        op.drop_table('brands')
        op.drop_index(op.f('ix_areas_slug'), table_name='areas')
        op.drop_index(op.f('ix_areas_name'), table_name='areas')
        op.drop_table('areas')

    if scope == 'system':
        op.drop_index(op.f('ix_public_user_grid_preferences_grid_id'), table_name='user_grid_preferences', schema='public')
        op.drop_table('user_grid_preferences', schema='public')
        op.drop_table('memberships', schema='public')
        op.drop_index(op.f('ix_public_global_tasks_title'), table_name='global_tasks', schema='public')
        op.drop_table('global_tasks', schema='public')
        op.drop_table('role_area_association', schema='public')
        op.drop_index(op.f('ix_public_global_users_username'), table_name='global_users', schema='public')
        op.drop_table('global_users', schema='public')
        op.drop_table('roles', schema='public')
        op.drop_index(op.f('ix_public_invites_code'), table_name='invites', schema='public')
        op.drop_table('invites', schema='public')
        op.drop_table('areas', schema='public')
        op.drop_index(op.f('ix_public_api_keys_key'), table_name='api_keys', schema='public')
        op.drop_table('api_keys', schema='public')
        op.drop_index(op.f('ix_shadow_backups_tenant_slug'), table_name='shadow_backups')
        op.drop_index(op.f('ix_shadow_backups_table_name'), table_name='shadow_backups')
        op.drop_table('shadow_backups')
        op.drop_index(op.f('ix_public_tenants_slug'), table_name='tenants', schema='public')
        op.drop_index(op.f('ix_public_tenants_name'), table_name='tenants', schema='public')
        op.drop_table('tenants', schema='public')
    # ### end Alembic commands ###
'''

with open(filepath, 'w') as f:
    f.write(content)
