FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código
COPY . .

# Expor porta 5000
EXPOSE 5000

# Rodar Flask
CMD ["python", "app.py"]
